name: Setup
description: Setup Node.js and install dependencies

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version-file: .nvmrc
        registry-url: "https://registry.npmjs.org"

    - name: Install dependencies
      uses: oven-sh/setup-bun@v2
      run: bun install